### PR TITLE
Issue-7: (chore) update information and logo in readme

### LINKED ISSUE #7: Added Logo and some info in README
Added Logo and some info in README

### PR DESCRIPTION
**Pull request by Ayush7614**
Fixes #7 
This PR Contains 
* Added info in main README
* Added Poster in README

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc  @joewxboy @t-fine

**Comment by Ayush7614** [comment]
cc @joewxboy

**Review by joewxboy — CHANGES_REQUESTED** [review]
Two things:

1. Please create an issue before submitting a PR and link it to the PR
2. @t-fine Do you have an official mission statement for open-horizon-services?

**Comment by Ayush7614** [comment]
Done @joewxboy

**Review by joewxboy — APPROVED** [review]
@t-fine Will need to review the Mission Statement

**Pull request merged**
